import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";

import { QueryClient } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });
// const quickSand = Quicksand({ subsets: ["latin"] });

const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <GoogleOAuthProvider clientId="149769373869-p2jvddjsbi0ab67d1u7b6q0adhcj606i.apps.googleusercontent.com">
            {children}
            <Toaster />
            {/* <ReactQueryDevtools /> */}
          </GoogleOAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
